local meteor_config = {
  {label = "meteor 1", contains_trash=true, summon_label = "Melon"},
  {label = "meteor 2", contains_trash=true, summon_label = "Emitter (LV)"},
  {label = "meteor 3", contains_trash=true, summon_label = "Sensor (LV)"},
  {label = "meteor 4", contains_trash=true, summon_label = "Exquisite Diamond"},
  {label = "meteor 5", contains_trash=true, summon_label = "End Stone"},
  {label = "meteor 6", contains_trash=true, summon_label = "Firestone Lens"},
  {label = "meteor 7", contains_trash=false, summon_label = "Sensor (HV)"},
  {label = "meteor 8", contains_trash=true, summon_label = "Heavy Duty Alloy Ingot T1"},
  {label = "meteor 9", contains_trash=false, summon_label = "Field Generator (LV)"},
  {label = "meteor 10", contains_trash=true, summon_label = "Cheese"},
  {label = "meteor 11", contains_trash=false, summon_label = "Nether Star"},
  {label = "meteor 12", contains_trash=true, summon_label = "Heavy Duty Alloy Ingot T2"},
  {label = "meteor 13", contains_trash=true, summon_label = "TNT"},
  {label = "meteor 14", contains_trash=true, summon_label = "Sanitizing Soap"},
  {label = "meteor 15", contains_trash=true, summon_label = "Heavy Duty Alloy Ingot T3"},
  {label = "meteor 16", contains_trash=true, summon_label = "Field Generator (HV)"},
  {label = "meteor 17", contains_trash=true, summon_label = "Heavy Duty Plate"},
  {label = "meteor 18", contains_trash=false, summon_label = "Advanced Replicator"},
  {label = "meteor 19", contains_trash=true, summon_label = "Field Generator (IV)"},
  {label = "meteor 20", contains_trash=false, summon_label = "Advanced Assembling Machine III"},
  {label = "meteor 21", contains_trash=false, summon_label = "Emitter (HV)"},
  {label = "meteor 22", contains_trash=false, summon_label = "Advanced Mass Fabricator IV"},
  {label = "meteor 23", contains_trash=true, summon_label = "Advanced Circuit Assembler II"},
  {label = "meteor 24", contains_trash=true, summon_label = "Soul Sand"},
  {label = "meteor 25", contains_trash=false, summon_label = "Advanced Mass Fabricator II"},
  {label = "meteor 26", contains_trash=true, summon_label = "Pufferfish"},
  {label = "meteor 27", contains_trash=true, summon_label = "Heavy Duty Plate Tier 4"},
  {label = "meteor 28", contains_trash=false, summon_label = "Boxinator"},
  {label = "meteor 29", contains_trash=true, summon_label = "Heavy Duty Plate Tier 5"},
  {label = "meteor 30", contains_trash=false, summon_label = "Advanced Scanner IV"},
  {label = "meteor 31", contains_trash=true, summon_label = "Heavy Duty Plate Tier 6"},
  {label = "meteor 32", contains_trash=false, summon_label = "Crystal Mainframe"},
  {label = "meteor 33", contains_trash=true, summon_label = "Heavy Duty Plate Tier 7"},
  {label = "meteor 34", contains_trash=true, summon_label = "Elite Recycler"},
  {label = "meteor 35", contains_trash=false, summon_label = "Wetware Supercomputer"},
  {label = "meteor 36", contains_trash=true, summon_label = "Heavy Duty Plate Tier 8"},
  {label = "meteor 37", contains_trash=false, summon_label = "Advanced Circuit Assembler VI"},
  {label = "meteor 38", contains_trash=false, summon_label = "Bloody Ichorium Fusion Casing"},
  {label = "meteor 39", contains_trash=false, summon_label = "Elite Mass Fabricator II"},
  {label = "meteor 40", contains_trash=false, summon_label = "Advanced Crop Synthesiser VII"},
  {label = "meteor 41", contains_trash=false, summon_label = "Ion Thruster Jet"},
  {label = "meteor 42", contains_trash=false, summon_label = "Space Mining Module MK-III"},
}
return meteor_config
